### ISSUE TITLE
Add stopPropagation()  to Jarvis\EventInterface

### ISSUE THREAD

**Issue by mickaelandrieu** [eric-chau/jarvis#17]
All actual events have both so I guess we can enforce and use this contract: what do you think @eric-chau?

**Comment by eric-chau** [comment]
@mickaelandrieu, to me `EventInterface::isPropagationStopped()` is enough cause it's the only method used by jarvis core. `::stopPropagation()` is not required to work. People may want to call it differently on their own events.

**Comment by mickaelandrieu** [comment]
ok ! this make sense (for now) :p
